routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });
// Route::group(['prefix' => 'api'], function () {
//     Route::group(['prefix' => 'user'], function () {
//         Route::get('',function(){
//             return 'ok';
//         });
//     });
// });
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');
$this->post('autenticar', 'Auth\LoginController@autenticar')->name('auth.autenticar');
// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');
Route::post('/kititens/fetchkit','Admin\KititensController@fetchkit')->name('kititens.fetchkit');

Route::post('/kititens/fetch','Admin\KititensController@fetch')->name('kititens.fetch');
Route::get('producaos/listproducao', 'Admin\ProducaosController@listproducao')->name('admin.producaos.listproducao');
Route::post('/producaos/fetchProducao','Admin\ProducaosController@fetchProducao')->name('producaos.fetchProducao');


Route::post('/entradanotas/lerxml','Admin\EntradanotasController@lerxml')->name('Admin.entradanotas.lerxml');
Route::post('/movimento/fetch','Admin\MovimentosController@fetch')->name('movimento.fetch');
Route::post('/movimento/Usuarioadiciona','Admin\MovimentosController@Usuarioadiciona')->name('movimento.Usuarioadiciona');

// Route::resource('movimentos', 'Admin\MovimentosController');
//NF-e
Route::post('/sats/store','NFeController@store')->name('Admin.sats.store');

//FIM NF-e
Route::post('/producaos/importartelaP','Admin\ProducaosController@importartelaP')->name('admin.producaos.importartelaP');
//Route::post('/entradanotas/preenchertela','Admin\EntradanotasController@preenchertela')->name('admin.entradanotas.preenchertela');
Route::post('/entradanotas/importartela','Admin\EntradanotasController@importartela')->name('admin.entradanotas.importartela');
// Route::post('/sats/pesquisaCliente','Admin\SatsController@pesquisaCliente')->name('Admin.sats.pesquisaCliente');
// Route::post('/sats/buscaNvenda','Admin\SatsController@buscaNvenda')->name('Admin.sats.buscaNvenda');


// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');


//fim atendimento
//conta a pagar
Route::post('/contaapagars/searchfornecedor','Admin\ContaapagarsController@searchfornecedor')->name('contaapagars.searchfornecedor');
Route::post('/contaapagars/searchcontacontabil','Admin\ContaapagarsController@searchcontacontabil')->name('contaapagars.searchcontacontabil');
Route::post('/contaapagars/searchusuario','Admin\ContaapagarsController@searchusuario')->name('contaapagars.searchusuario');
//fim contas a pagar
//contas a receber
Route::post('/contarecebers/searchcliente','Admin\ContarecebersController@searchcliente')->name('contarecebers.searchcliente');
Route::post('/contarecebers/searchcontacontabil','Admin\ContarecebersController@searchcontacontabil')->name('contarecebers.searchcontacontabil');
Route::post('/contarecebers/searchusuario','Admin\ContarecebersController@searchusuario')->name('contarecebers.searchusuario');
// fim contas a receber
//despesa
Route::post('/despesas/searchfornecedor','Admin\DespesasController@searchfornecedor')->name('despesas.searchfornecedor');
Route::post('/despesas/searchcontacontabil','Admin\DespesasController@searchcontacontabil')->name('despesas.searchcontacontabil');
Route::post('/despesas/searchusuario','Admin\DespesasController@searchusuario')->name('despesas.searchusuario');
// fim despesa

Route::post('/promissorias/searchcliente','Admin\PromissoriasController@searchcliente')->name('promissorias.searchcliente');
Route::post('/promissorias/searchusuario','Admin\PromissoriasController@searchusuario')->name('promissorias.searchusuario');
// fim promissorias
// Route::post('/animals/searchcliente', ['uses' => 'Admin\AnimalsController@searchcliente', 'as' => 'animals.searchcliente']);
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
   
    Route::resource('empresas', 'Admin\EmpresasController');
    Route::post('empresas_mass_destroy', ['uses' => 'Admin\EmpresasController@massDestroy', 'as' => 'empresas.mass_destroy']);
    Route::post('empresas_restore/{id}', ['uses' => 'Admin\EmpresasController@restore', 'as' => 'empresas.restore']);
    Route::delete('empresas_perma_del/{id}', ['uses' => 'Admin\EmpresasController@perma_del', 'as' => 'empresas.perma_del']);
 
    Route::resource('clientes', 'Admin\ClientesController');
    Route::post('clientes_mass_destroy', ['uses' => 'Admin\ClientesController@massDestroy', 'as' => 'clientes.mass_destroy']);
    Route::post('clientes_restore/{id}', ['uses' => 'Admin\ClientesController@restore', 'as' => 'clientes.restore']);
    Route::delete('clientes_perma_del/{id}', ['uses' => 'Admin\ClientesController@perma_del', 'as' => 'clientes.perma_del']);
  
    Route::resource('agendahorarios', 'Admin\AgendahorariosController');
    Route::post('agendahorarios_mass_destroy', ['uses' => 'Admin\AgendahorariosController@massDestroy', 'as' => 'agendahorarios.mass_destroy']);
    Route::post('agendahorarios_restore/{id}', ['uses' => 'Admin\AgendahorariosController@restore', 'as' => 'agendahorarios.restore']);
    Route::delete('agendahorarios_perma_del/{id}', ['uses' => 'Admin\AgendahorariosController@perma_del', 'as' => 'agendahorarios.perma_del']);
    Route::resource('produtos', 'Admin\ProdutosController');
    Route::post('produtos_mass_destroy', ['uses' => 'Admin\ProdutosController@massDestroy', 'as' => 'produtos.mass_destroy']);
    Route::post('produtos_restore/{id}', ['uses' => 'Admin\ProdutosController@restore', 'as' => 'produtos.restore']);
    Route::delete('produtos_perma_del/{id}', ['uses' => 'Admin\ProdutosController@perma_del', 'as' => 'produtos.perma_del']);
    Route::resource('depositos', 'Admin\DepositosController');
    Route::post('depositos_mass_destroy', ['uses' => 'Admin\DepositosController@massDestroy', 'as' => 'depositos.mass_destroy']);
    Route::post('depositos_restore/{id}', ['uses' => 'Admin\DepositosController@restore', 'as' => 'depositos.restore']);
    Route::delete('depositos_perma_del/{id}', ['uses' => 'Admin\DepositosController@perma_del', 'as' => 'depositos.perma_del']);
    Route::resource('fornecedors', 'Admin\FornecedorsController');
    Route::post('fornecedors_mass_destroy', ['uses' => 'Admin\FornecedorsController@massDestroy', 'as' => 'fornecedors.mass_destroy']);
    Route::post('fornecedors_restore/{id}', ['uses' => 'Admin\FornecedorsController@restore', 'as' => 'fornecedors.restore']);
    Route::delete('fornecedors_perma_del/{id}', ['uses' => 'Admin\FornecedorsController@perma_del', 'as' => 'fornecedors.perma_del']);
  
    Route::resource('referencias', 'Admin\ReferenciasController');
    Route::post('referencias_mass_destroy', ['uses' => 'Admin\ReferenciasController@massDestroy', 'as' => 'referencias.mass_destroy']);
    Route::post('referencias_restore/{id}', ['uses' => 'Admin\ReferenciasController@restore', 'as' => 'referencias.restore']);
    Route::delete('referencias_perma_del/{id}', ['uses' => 'Admin\ReferenciasController@perma_del', 'as' => 'referencias.perma_del']);
    Route::resource('cors', 'Admin\CorsController');
    Route::post('cors_mass_destroy', ['uses' => 'Admin\CorsController@massDestroy', 'as' => 'cors.mass_destroy']);
    Route::post('cors_restore/{id}', ['uses' => 'Admin\CorsController@restore', 'as' => 'cors.restore']);
    Route::delete('cors_perma_del/{id}', ['uses' => 'Admin\CorsController@perma_del', 'as' => 'cors.perma_del']);
   
    Route::resource('tamanhos', 'Admin\TamanhosController');
    Route::post('tamanhos_mass_destroy', ['uses' => 'Admin\TamanhosController@massDestroy', 'as' => 'tamanhos.mass_destroy']);
    Route::post('tamanhos_restore/{id}', ['uses' => 'Admin\TamanhosController@restore', 'as' => 'tamanhos.restore']);
    Route::delete('tamanhos_perma_del/{id}', ['uses' => 'Admin\TamanhosController@perma_del', 'as' => 'tamanhos.perma_del']);

    Route::resource('entradanotas', 'Admin\EntradanotasController');
    Route::post('entradanotas_mass_destroy', ['uses' => 'Admin\EntradanotasController@massDestroy', 'as' => 'entradanotas.mass_destroy']);
    Route::post('entradanotas_restore/{id}', ['uses' => 'Admin\EntradanotasController@restore', 'as' => 'entradanotas.restore']);
    Route::delete('entradanotas_perma_del/{id}', ['uses' => 'Admin\EntradanotasController@perma_del', 'as' => 'entradanotas.perma_del']);
    
    Route::resource('devolucaos', 'Admin\DevolucaosController');
    Route::post('devolucaos_mass_destroy', ['uses' => 'Admin\DevolucaosController@massDestroy', 'as' => 'devolucaos.mass_destroy']);
    Route::post('devolucaos_restore/{id}', ['uses' => 'Admin\DevolucaosController@restore', 'as' => 'devolucaos.restore']);

resources/views/actionsTemplate.blade.php
@can($gateKey.'view')
    <a href="{{ route($routeKey.'.show', $row->id) }}"
       class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
@endcan
@can($gateKey.'edit')
    <a href="{{ route($routeKey.'.edit', $row->id) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
@endcan
@can($gateKey.'delete')
    {!! Form::open(array(
        'style' => 'display: inline-block;',
        'method' => 'DELETE',
        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
        'route' => [$routeKey.'.destroy', $row->id])) !!}
    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
    {!! Form::close() !!}
@endcan

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div id="HNome" class="panel-heading center">
                    <h4 id="TNome">DASHBOARD</h4></div>

                <div class="panel-body">
                    {{-- @lang('quickadmin.qa_dashboard_text') --}}
                 
                            <!-- ./col -->
                            {{-- <div class="col-lg-3 col-xs-6">
                                <!-- small box -->
                                <div class="small-box bg-aqua">
                                  <div class="inner">
                                  <h3>{{$total_vendas}}</h3>
                      
                                    <p>VENDAS</p>
                                  </div>
                                  <div class="icon">
                                      
                                    <i class="fa fa-shopping-cart"></i>
                                  </div>
                                  <a href="{{ route('admin.produtos.index') }}" class="small-box-footer">
                                    VER <i class="fa fa-arrow-circle-right"></i>
                                  </a>I
                                </div>
                              </div> --}}
                              {{-- <div class="col-lg-3 col-xs-6">
                                  <!-- small box -->
                                  <div class="small-box bg-blue" style="background-color:skyblue">
                                    <div class="inner">
                                    <h3>{{$total_item}}</h3>
                        
                                      <p>ITENS VENDIDOS</p>
                                    </div>
                                    <div class="icon">
                                      <i class="fa fa-area-chart"></i>
                                    </div>
                                    <a href="{{ route('admin.produtos.index') }}" class="small-box-footer">
                                      VER <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                  </div>
                                </div> --}}
                              <div class="col-lg-3 col-xs-6">
                                  <!-- small box -->
                                  <div class="small-box bg-aqua">
                                    <div class="inner">
                                    <h3>{{$total_produtos}}</h3>
                        
                                      <p>PRODUTOS</p>
                                    </div>
                                    <div class="icon">
                                      <i class="fa fa-shopping-basket"></i>
                                    </div>
                                    <a href="{{ route('admin.produtos.index') }}" class="small-box-footer">
                                      VER <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                  </div>
                                </div>
                                <div class="col-lg-3 col-xs-6">
                                    <!-- small box -->
                                    <div class="small-box bg-green">
                                      <div class="inner">
                                      <h3>{{$total_deposito}}</h3>
                          
                                        <p>DEPÓSITOS</p>
                                      </div>
                                      <div class="icon">
                                          <i class="ion ion-stats-bars"></i>
                                      </div>
                                      <a href="{{ route('admin.produtos.index') }}" class="small-box-footer">
                                        VER <i class="fa fa-arrow-circle-right"></i>
                                      </a>
                                    </div>
                                  </div>
                                <div class="col-lg-3 col-xs-6">
                                    <!-- small box -->
                                    <div class="small-box bg-yellow">
                                      <div class="inner">
                                      <h3>{{$total_counts}}</h3>
                          
                                        <p>USUÁRIOS</p>
                                      </div>
                                      <div class="icon">
                                        <i class="ion ion-person-add"></i>
                                      </div>
                                      <a href="{{ route('admin.users.index') }}" class="small-box-footer">
                                          VER <i class="fa fa-arrow-circle-right"></i>
                                      </a>
                                    </div>
                                  </div>
                                  <div class="col-lg-3 col-xs-6">
                                      <!-- small box -->
                                      <div class="small-box bg-red">
                                        <div class="inner">
                                            <h3>{{$total_movimento}}</h3>
                            
                                          <p>MOVIMENTOS</p>
                                        </div>
                                        <div class="icon">
                                          <i class="ion ion-pie-graph"></i>
                                        </div>
                                        <a href="#" class="small-box-footer">
                                          VER <i class="fa fa-arrow-circle-right"></i>
                                        </a>
                                      </div>
                                    </div>
                                    
                </div>
        
                </div>
                <div class="panel panel-primary">
                    <div id="HNome" class="panel-heading center">
                      <h4 id="TNome">ACESSO RÁPIDO</h4></div>
    
                    <div class="panel-body">
                        <div class="box-body">
                           
                            <a class="btn btn-app" style="height:90px;width:100px" style="height:90px;width:100px"  href="{{ route('admin.agendatelefonicas.index') }}">
                              <i style="font-size:40px" class="fa fa-phone"></i> AGENDA
                            </a>
                            <a class="btn btn-app" style="height:90px;width:100px" href="{{ route('admin.empresas.index') }}">
                              <i style="font-size:40px" class="fa fa-building"></i> EMPRESA
                            </a>
                            <a class="btn btn-app" style="height:90px;width:100px" href="{{ route('admin.fornecedors.index') }}">
                              <i style="font-size:40px" class="fa fa-truck"></i> FORNECEDOR
                            </a>
                            <a class="btn btn-app" style="height:90px;width:100px" href="{{ route('admin.users.index') }}">
                              <i style="font-size:40px" class="fa fa-user"></i> USUÁRIO
                            </a>
                            <a class="btn btn-app" style="height:90px;width:100px" href="{{ route('admin.produtos.index') }}">
                              <i style="font-size:40px" class="fa fa-shopping-basket"></i> PRODUTO
                            </a>
                            <a class="btn btn-app" style="height:90px;width:100px" href="{{ route('admin.producaos.index') }}">
                              <i style="font-size:40px" class="fa fa-shopping-bag"></i> PRODUÇÃO
                            </a>
                                  <a class="btn btn-app" style="height:90px;width:100px" href="{{ route('admin.kititens.index') }}">
                              <span class="badge bg-yellow"></span>
                              <i style="font-size:40px" class="fa fa-flask"></i>COMPOSIÇÃO
                            </a>
                            {{-- <a class="btn btn-app" style="height:90px;width:100px" href="{{ route('admin.entradanotas.index') }}">
                              <span class="badge bg-yellow"></span>
                              <i style="font-size:40px" class="fa fa-file-text"></i> NOTA
                            </a> --}}
                          
                          </div>
                                                                      
                    </div>
                    </div>
            </div>
        </div>
    </div>
 
    
@endsection

resources/views/restoreTemplate.blade.php
@can($gateKey.'delete')
    {!! Form::open(array(
        'style' => 'display: inline-block;',
        'method' => 'POST',
        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
        'route' => [$routeKey.'.restore', $row->id])) !!}
    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
    {!! Form::close() !!}
@endcan
@can($gateKey.'delete')
    {!! Form::open(array(
        'style' => 'display: inline-block;',
        'method' => 'DELETE',
        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
        'route' => [$routeKey.'.perma_del', $row->id])) !!}
    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
    {!! Form::close() !!}
@endcan